# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/laravel

    steps:
      - checkout
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-
      - run: yarn install
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: touch database/testing.sqlite
      - run: php artisan migrate --env=testing --database=sqlite_testing --force

  test:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/laravel
    steps:
      - run:
          name: PHPUnit
          command: |
            mkdir -p ~/phpunit
            ./vendor/bin/phpunit --log-junit ~/build/phpunit/junit.xml
          when: always
      - store_test_results:
          path: ~/build/phpunit
      - store_artifacts:
          path: ~/build/phpunit
  coverage:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/laravel
    steps:
      - run:
          name: Generate coverage
          command: ./vendor/bin/phpunit --coverage-clover ~/build/phpunit/coverage/xml
      - run:
          name: Upload coverage to Codacy
          command: ./vendor/bin/codacycoverage clover ~/build/phpunit/coverage/xml
      - store_test_results:
          path: ~/build/phpunit
      - store_artifacts:
          path: ~/build/phpunit
  docs:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/laravel
    steps:
       - run: curl -O http://get.sensiolabs.org/sami.phar -o ./sami.phar
       - run:
           name: Generate documentation
           command: php sami.phar update sami.php
       - store_test_results:
            path: ~/build/docs
       - store_artifacts:
            path: ~/build/docs


workflows:
  version: 2
  everything:
    jobs:
      - build
      - test:
           requires:
               - build
      - coverage:
           requires:
               - build
      - docs:
           requires:
               - build
  test_and_coverage:
    jobs:
      - build
      - test:
           requires:
               - build
      - coverage:
           requires:
               - build
