<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateVocabulary extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('vocabulary', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('course');
            $table->string('kana');
            $table->string('kanji')->nullable();
            $table->string('polish');
        });

        DB::table('vocabulary')->insert(["id" => 1,"course" => 5,"kana" => "かめ","kanji" => "亀", "polish" => "żółw"]);
        DB::table('vocabulary')->insert(["id" => 2,"course" => 5,"kana" => "うさぎ","kanji" => "兎", "polish" => "królik"]);
        DB::table('vocabulary')->insert(["id" => 3,"course" => 5,"kana" => "えび","kanji" => "海老", "polish" => "krewetka"]);
        DB::table('vocabulary')->insert(["id" => 4,"course" => 5,"kana" => "かえる","kanji" => "蛙", "polish" => "żaba"]);
        DB::table('vocabulary')->insert(["id" => 5,"course" => 5,"kana" => "とかげ","kanji" => "蜥蜴", "polish" => "jaszczurka"]);
        DB::table('vocabulary')->insert(["id" => 6,"course" => 5,"kana" => "ぞう","kanji" => "象", "polish" => "słoń"]);
        DB::table('vocabulary')->insert(["id" => 7,"course" => 5,"kana" => "ライオン","kanji" => "ライオン", "polish" => "lew"]);
        DB::table('vocabulary')->insert(["id" => 8,"course" => 5,"kana" => "ねずみ","kanji" => "鼠", "polish" => "mysz"]);
        DB::table('vocabulary')->insert(["id" => 9,"course" => 5,"kana" => "さる","kanji" => "猿", "polish" => "małpa"]);
        DB::table('vocabulary')->insert(["id" => 10,"course" => 5,"kana" => "へび","kanji" => "蛇", "polish" => "wąż"]);
        DB::table('vocabulary')->insert(["id" => 11,"course" => 5,"kana" => "さかな","kanji" => "魚", "polish" => "ryba"]);
        DB::table('vocabulary')->insert(["id" => 12,"course" => 5,"kana" => "とり","kanji" => "鳥", "polish" => "ptak"]);
        DB::table('vocabulary')->insert(["id" => 13,"course" => 5,"kana" => "いぬ","kanji" => "犬", "polish" => "pies"]);
        DB::table('vocabulary')->insert(["id" => 14,"course" => 5,"kana" => "ねこ","kanji" => "猫", "polish" => "kot"]);
        DB::table('vocabulary')->insert(["id" => 15,"course" => 3,"kana" => "きょうし","kanji" => "教師", "polish" => "nauczyciel"]);
        DB::table('vocabulary')->insert(["id" => 16,"course" => 3,"kana" => "いしゃ","kanji" => "医者", "polish" => "lekarz"]);
        DB::table('vocabulary')->insert(["id" => 17,"course" => 3,"kana" => "かんごし","kanji" => "看護師", "polish" => "pielęgniarka"]);
        DB::table('vocabulary')->insert(["id" => 18,"course" => 3,"kana" => "べんごし","kanji" => "弁護士", "polish" => "prawnik"]);
        DB::table('vocabulary')->insert(["id" => 19,"course" => 3,"kana" => "かしゅ","kanji" => "歌手", "polish" => "piosenkarz"]);
        DB::table('vocabulary')->insert(["id" => 20,"course" => 3,"kana" => "はいゆう","kanji" => "俳優", "polish" => "aktor"]);
        DB::table('vocabulary')->insert(["id" => 21,"course" => 3,"kana" => "げいじゅつか","kanji" => "芸術家", "polish" => "artysta"]);
        DB::table('vocabulary')->insert(["id" => 22,"course" => 3,"kana" => "プログラマ","kanji" => "プログラマ", "polish" => "programista"]);
        DB::table('vocabulary')->insert(["id" => 23,"course" => 3,"kana" => "さっか","kanji" => "作家", "polish" => "pisarz"]);
        DB::table('vocabulary')->insert(["id" => 24,"course" => 3,"kana" => "おとこ","kanji" => "男", "polish" => "mężczyzna"]);
        DB::table('vocabulary')->insert(["id" => 25,"course" => 3,"kana" => "ひと","kanji" => "人", "polish" => "człowiek"]);
        DB::table('vocabulary')->insert(["id" => 26,"course" => 4,"kana" => "えき","kanji" => "駅", "polish" => "stacja"]);
        DB::table('vocabulary')->insert(["id" => 27,"course" => 4,"kana" => "だいがく","kanji" => "大学", "polish" => "uniwersytet"]);
        DB::table('vocabulary')->insert(["id" => 28,"course" => 4,"kana" => "がくせい","kanji" => "学生", "polish" => "student"]);
        DB::table('vocabulary')->insert(["id" => 29,"course" => 4,"kana" => "みんな","kanji" => "皆", "polish" => "wszyscy"]);
        DB::table('vocabulary')->insert(["id" => 30,"course" => 4,"kana" => "わすれる","kanji" => "忘れる", "polish" => "zapominać"]);
        DB::table('vocabulary')->insert(["id" => 31,"course" => 4,"kana" => "おぼえる","kanji" => "覚える", "polish" => "pamiętać"]);
        DB::table('vocabulary')->insert(["id" => 32,"course" => 4,"kana" => "おどる","kanji" => "踊る", "polish" => "tańczyć"]);
        DB::table('vocabulary')->insert(["id" => 33,"course" => 4,"kana" => "かしゅ","kanji" => "歌手", "polish" => "piosenkarz"]);
        DB::table('vocabulary')->insert(["id" => 34,"course" => 4,"kana" => "しょうらい","kanji" => "将来", "polish" => "przyszłość"]);
        DB::table('vocabulary')->insert(["id" => 35,"course" => 4,"kana" => "それで","kanji" => "それで", "polish" => "zatem"]);
        DB::table('vocabulary')->insert(["id" => 36,"course" => 4,"kana" => "かいわ","kanji" => "会話", "polish" => "rozmowa"]);
        DB::table('vocabulary')->insert(["id" => 37,"course" => 4,"kana" => "しゅうかん","kanji" => "習慣", "polish" => "zwyczaj"]);
        DB::table('vocabulary')->insert(["id" => 38,"course" => 4,"kana" => "そら","kanji" => "空", "polish" => "niebo"]);
        DB::table('vocabulary')->insert(["id" => 39,"course" => 4,"kana" => "よる","kanji" => "夜", "polish" => "noc"]);
        DB::table('vocabulary')->insert(["id" => 40,"course" => 4,"kana" => "はなび","kanji" => "花火", "polish" => "fajerwerki"]);
        DB::table('vocabulary')->insert(["id" => 41,"course" => 4,"kana" => "どうぶつ","kanji" => "動物", "polish" => "zwierzę"]);
        DB::table('vocabulary')->insert(["id" => 42,"course" => 4,"kana" => "ばしょ","kanji" => "場所", "polish" => "miejsce"]);
        DB::table('vocabulary')->insert(["id" => 43,"course" => 4,"kana" => "お","kanji" => "お", "polish" => "o"]);
        DB::table('vocabulary')->insert(["id" => 44,"course" => 4,"kana" => "え","kanji" => "え", "polish" => "e"]);
        DB::table('vocabulary')->insert(["id" => 45,"course" => 4,"kana" => "う","kanji" => "う", "polish" => "u"]);
        DB::table('vocabulary')->insert(["id" => 46,"course" => 4,"kana" => "い","kanji" => "い", "polish" => "i"]);
        DB::table('vocabulary')->insert(["id" => 47,"course" => 4,"kana" => "あ","kanji" => "あ", "polish" => "a"]);
        DB::table('vocabulary')->insert(["id" => 48,"course" => 4,"kana" => "か","kanji" => "か", "polish" => "ka"]);
        DB::table('vocabulary')->insert(["id" => 49,"course" => 4,"kana" => "き","kanji" => "き", "polish" => "ki"]);
        DB::table('vocabulary')->insert(["id" => 50,"course" => 4,"kana" => "く","kanji" => "く", "polish" => "ku"]);
        DB::table('vocabulary')->insert(["id" => 51,"course" => 4,"kana" => "け","kanji" => "け", "polish" => "ke"]);
        DB::table('vocabulary')->insert(["id" => 52,"course" => 4,"kana" => "こ","kanji" => "こ", "polish" => "ko"]);
        DB::table('vocabulary')->insert(["id" => 53,"course" => 4,"kana" => "さ","kanji" => "さ", "polish" => "sa"]);
        DB::table('vocabulary')->insert(["id" => 54,"course" => 4,"kana" => "しんぶん","kanji" => "新聞", "polish" => "gazeta"]);
        DB::table('vocabulary')->insert(["id" => 55,"course" => 4,"kana" => "おゆ","kanji" => "お湯", "polish" => "gorąca woda"]);
        DB::table('vocabulary')->insert(["id" => 56,"course" => 4,"kana" => "じむしょ","kanji" => "事務所", "polish" => "biuro"]);
        DB::table('vocabulary')->insert(["id" => 57,"course" => 4,"kana" => "かん","kanji" => "缶", "polish" => "puszka"]);
        DB::table('vocabulary')->insert(["id" => 58,"course" => 4,"kana" => "びん","kanji" => "瓶", "polish" => "butelka"]);
        DB::table('vocabulary')->insert(["id" => 59,"course" => 4,"kana" => "うちゅう","kanji" => "宇宙", "polish" => "kosmos"]);
        DB::table('vocabulary')->insert(["id" => 60,"course" => 4,"kana" => "きもの","kanji" => "着物", "polish" => "kimono"]);
        DB::table('vocabulary')->insert(["id" => 61,"course" => 7,"kana" => "おじいさん","kanji" => "お祖父さん", "polish" => "dziadek"]);
        DB::table('vocabulary')->insert(["id" => 62,"course" => 7,"kana" => "おばあさん","kanji" => "お祖母さん", "polish" => "babcia"]);
        DB::table('vocabulary')->insert(["id" => 63,"course" => 7,"kana" => "いもうと","kanji" => "妹", "polish" => "młodsza siostra"]);
        DB::table('vocabulary')->insert(["id" => 64,"course" => 7,"kana" => "あね","kanji" => "姉", "polish" => "starsza siostra"]);
        DB::table('vocabulary')->insert(["id" => 65,"course" => 7,"kana" => "おとうと","kanji" => "弟", "polish" => "młodszy brat"]);
        DB::table('vocabulary')->insert(["id" => 66,"course" => 7,"kana" => "あに","kanji" => "兄", "polish" => "starszy brat"]);
        DB::table('vocabulary')->insert(["id" => 67,"course" => 7,"kana" => "むすめ","kanji" => "娘", "polish" => "córka"]);
        DB::table('vocabulary')->insert(["id" => 68,"course" => 7,"kana" => "むすこ","kanji" => "息子", "polish" => "syn"]);
        DB::table('vocabulary')->insert(["id" => 69,"course" => 7,"kana" => "おとうさん","kanji" => "お父さん", "polish" => "(twój) tata"]);
        DB::table('vocabulary')->insert(["id" => 70,"course" => 7,"kana" => "ちち","kanji" => "父", "polish" => "(mój) tata"]);
        DB::table('vocabulary')->insert(["id" => 71,"course" => 7,"kana" => "おかあさん","kanji" => "お母さん", "polish" => "(twoja) mama"]);
        DB::table('vocabulary')->insert(["id" => 72,"course" => 7,"kana" => "はは","kanji" => "母", "polish" => "(moja) mama"]);
        DB::table('vocabulary')->insert(["id" => 73,"course" => 1,"kana" => "や","kanji" => "や", "polish" => "ya"]);
        DB::table('vocabulary')->insert(["id" => 74,"course" => 1,"kana" => "ゆ","kanji" => "ゆ", "polish" => "yu"]);
        DB::table('vocabulary')->insert(["id" => 75,"course" => 1,"kana" => "よ","kanji" => "よ", "polish" => "yo"]);
        DB::table('vocabulary')->insert(["id" => 76,"course" => 1,"kana" => "わ","kanji" => "わ", "polish" => "wa"]);
        DB::table('vocabulary')->insert(["id" => 77,"course" => 1,"kana" => "を","kanji" => "を", "polish" => "wo"]);
        DB::table('vocabulary')->insert(["id" => 78,"course" => 1,"kana" => "は","kanji" => "は", "polish" => "ha"]);
        DB::table('vocabulary')->insert(["id" => 79,"course" => 1,"kana" => "ひ","kanji" => "ひ", "polish" => "hi"]);
        DB::table('vocabulary')->insert(["id" => 80,"course" => 1,"kana" => "ふ","kanji" => "ふ", "polish" => "fu"]);
        DB::table('vocabulary')->insert(["id" => 81,"course" => 1,"kana" => "へ","kanji" => "へ", "polish" => "he"]);
        DB::table('vocabulary')->insert(["id" => 82,"course" => 1,"kana" => "ほ","kanji" => "ほ", "polish" => "ho"]);
        DB::table('vocabulary')->insert(["id" => 83,"course" => 1,"kana" => "ぱ","kanji" => "ぱ", "polish" => "pa"]);
        DB::table('vocabulary')->insert(["id" => 84,"course" => 1,"kana" => "ぴ","kanji" => "ぴ", "polish" => "pi"]);
        DB::table('vocabulary')->insert(["id" => 85,"course" => 1,"kana" => "ぷ","kanji" => "ぷ", "polish" => "pu"]);
        DB::table('vocabulary')->insert(["id" => 86,"course" => 1,"kana" => "ぺ","kanji" => "ぺ", "polish" => "pe"]);
        DB::table('vocabulary')->insert(["id" => 87,"course" => 1,"kana" => "ぽ","kanji" => "ぽ", "polish" => "po"]);
        DB::table('vocabulary')->insert(["id" => 88,"course" => 1,"kana" => "が","kanji" => "が", "polish" => "ga"]);
        DB::table('vocabulary')->insert(["id" => 89,"course" => 1,"kana" => "ぎ","kanji" => "ぎ", "polish" => "gi"]);
        DB::table('vocabulary')->insert(["id" => 90,"course" => 1,"kana" => "ぐ","kanji" => "ぐ", "polish" => "gu"]);
        DB::table('vocabulary')->insert(["id" => 91,"course" => 1,"kana" => "げ","kanji" => "げ", "polish" => "ge"]);
        DB::table('vocabulary')->insert(["id" => 92,"course" => 1,"kana" => "ご","kanji" => "ご", "polish" => "go"]);
        DB::table('vocabulary')->insert(["id" => 93,"course" => 1,"kana" => "だ","kanji" => "だ", "polish" => "da"]);
        DB::table('vocabulary')->insert(["id" => 94,"course" => 1,"kana" => "づ","kanji" => "づ", "polish" => "du"]);
        DB::table('vocabulary')->insert(["id" => 95,"course" => 1,"kana" => "で","kanji" => "で", "polish" => "de"]);
        DB::table('vocabulary')->insert(["id" => 96,"course" => 1,"kana" => "ど","kanji" => "ど", "polish" => "do"]);
        DB::table('vocabulary')->insert(["id" => 97,"course" => 1,"kana" => "ら","kanji" => "ら", "polish" => "ra"]);
        DB::table('vocabulary')->insert(["id" => 98,"course" => 1,"kana" => "り","kanji" => "り", "polish" => "ri"]);
        DB::table('vocabulary')->insert(["id" => 99,"course" => 1,"kana" => "る","kanji" => "る", "polish" => "ru"]);
        DB::table('vocabulary')->insert(["id" => 100,"course" => 1,"kana" => "れ","kanji" => "れ", "polish" => "re"]);
        DB::table('vocabulary')->insert(["id" => 101,"course" => 1,"kana" => "ろ","kanji" => "ろ", "polish" => "ro"]);
        DB::table('vocabulary')->insert(["id" => 102,"course" => 1,"kana" => "ざ","kanji" => "ざ", "polish" => "za"]);
        DB::table('vocabulary')->insert(["id" => 103,"course" => 1,"kana" => "じ","kanji" => "じ", "polish" => "ji"]);
        DB::table('vocabulary')->insert(["id" => 104,"course" => 1,"kana" => "ず","kanji" => "ず", "polish" => "zu"]);
        DB::table('vocabulary')->insert(["id" => 105,"course" => 1,"kana" => "ぜ","kanji" => "ぜ", "polish" => "ze"]);
        DB::table('vocabulary')->insert(["id" => 106,"course" => 1,"kana" => "ぞ","kanji" => "ぞ", "polish" => "zo"]);
        DB::table('vocabulary')->insert(["id" => 107,"course" => 1,"kana" => "ん","kanji" => "ん", "polish" => "n"]);
        DB::table('vocabulary')->insert(["id" => 108,"course" => 1,"kana" => "つ","kanji" => "つ", "polish" => "tsu"]);
        DB::table('vocabulary')->insert(["id" => 109,"course" => 1,"kana" => "て","kanji" => "て", "polish" => "te"]);
        DB::table('vocabulary')->insert(["id" => 110,"course" => 1,"kana" => "と","kanji" => "と", "polish" => "to"]);
        DB::table('vocabulary')->insert(["id" => 111,"course" => 1,"kana" => "な","kanji" => "な", "polish" => "na"]);
        DB::table('vocabulary')->insert(["id" => 112,"course" => 1,"kana" => "に","kanji" => "に", "polish" => "ni"]);
        DB::table('vocabulary')->insert(["id" => 113,"course" => 1,"kana" => "ぬ","kanji" => "ぬ", "polish" => "nu"]);
        DB::table('vocabulary')->insert(["id" => 114,"course" => 1,"kana" => "ね","kanji" => "ね", "polish" => "ne"]);
        DB::table('vocabulary')->insert(["id" => 115,"course" => 1,"kana" => "の","kanji" => "の", "polish" => "no"]);
        DB::table('vocabulary')->insert(["id" => 116,"course" => 1,"kana" => "ま","kanji" => "ま", "polish" => "ma"]);
        DB::table('vocabulary')->insert(["id" => 117,"course" => 1,"kana" => "み","kanji" => "み", "polish" => "mi"]);
        DB::table('vocabulary')->insert(["id" => 118,"course" => 1,"kana" => "む","kanji" => "む", "polish" => "mu"]);
        DB::table('vocabulary')->insert(["id" => 119,"course" => 1,"kana" => "め","kanji" => "め", "polish" => "me"]);
        DB::table('vocabulary')->insert(["id" => 120,"course" => 1,"kana" => "も","kanji" => "も", "polish" => "mo"]);
        DB::table('vocabulary')->insert(["id" => 121,"course" => 1,"kana" => "お","kanji" => "お", "polish" => "o"]);
        DB::table('vocabulary')->insert(["id" => 122,"course" => 1,"kana" => "え","kanji" => "え", "polish" => "e"]);
        DB::table('vocabulary')->insert(["id" => 123,"course" => 1,"kana" => "う","kanji" => "う", "polish" => "u"]);
        DB::table('vocabulary')->insert(["id" => 124,"course" => 1,"kana" => "い","kanji" => "い", "polish" => "i"]);
        DB::table('vocabulary')->insert(["id" => 125,"course" => 1,"kana" => "あ","kanji" => "あ", "polish" => "a"]);
        DB::table('vocabulary')->insert(["id" => 126,"course" => 1,"kana" => "か","kanji" => "か", "polish" => "ka"]);
        DB::table('vocabulary')->insert(["id" => 127,"course" => 1,"kana" => "き","kanji" => "き", "polish" => "ki"]);
        DB::table('vocabulary')->insert(["id" => 128,"course" => 1,"kana" => "く","kanji" => "く", "polish" => "ku"]);
        DB::table('vocabulary')->insert(["id" => 129,"course" => 1,"kana" => "け","kanji" => "け", "polish" => "ke"]);
        DB::table('vocabulary')->insert(["id" => 130,"course" => 1,"kana" => "こ","kanji" => "こ", "polish" => "ko"]);
        DB::table('vocabulary')->insert(["id" => 131,"course" => 1,"kana" => "さ","kanji" => "さ", "polish" => "sa"]);
        DB::table('vocabulary')->insert(["id" => 132,"course" => 1,"kana" => "し","kanji" => "し", "polish" => "shi"]);
        DB::table('vocabulary')->insert(["id" => 133,"course" => 1,"kana" => "す","kanji" => "す", "polish" => "su"]);
        DB::table('vocabulary')->insert(["id" => 134,"course" => 1,"kana" => "せ","kanji" => "せ", "polish" => "se"]);
        DB::table('vocabulary')->insert(["id" => 135,"course" => 1,"kana" => "そ","kanji" => "そ", "polish" => "so"]);
        DB::table('vocabulary')->insert(["id" => 136,"course" => 1,"kana" => "た","kanji" => "た", "polish" => "ta"]);
        DB::table('vocabulary')->insert(["id" => 137,"course" => 1,"kana" => "ち","kanji" => "ち", "polish" => "chi"]);
        DB::table('vocabulary')->insert(["id" => 138,"course" => 2,"kana" => "オ","kanji" => "オ", "polish" => "o"]);
        DB::table('vocabulary')->insert(["id" => 139,"course" => 2,"kana" => "エ","kanji" => "エ", "polish" => "e"]);
        DB::table('vocabulary')->insert(["id" => 140,"course" => 2,"kana" => "ウ","kanji" => "ウ", "polish" => "u"]);
        DB::table('vocabulary')->insert(["id" => 141,"course" => 2,"kana" => "イ","kanji" => "イ", "polish" => "i"]);
        DB::table('vocabulary')->insert(["id" => 142,"course" => 2,"kana" => "ア","kanji" => "ア", "polish" => "a"]);
        DB::table('vocabulary')->insert(["id" => 143,"course" => 2,"kana" => "カ","kanji" => "カ", "polish" => "ka"]);
        DB::table('vocabulary')->insert(["id" => 144,"course" => 2,"kana" => "キ","kanji" => "キ", "polish" => "ki"]);
        DB::table('vocabulary')->insert(["id" => 145,"course" => 2,"kana" => "ク","kanji" => "ク", "polish" => "ku"]);
        DB::table('vocabulary')->insert(["id" => 146,"course" => 2,"kana" => "ケ","kanji" => "ケ", "polish" => "ke"]);
        DB::table('vocabulary')->insert(["id" => 147,"course" => 2,"kana" => "コ","kanji" => "コ", "polish" => "ko"]);
        DB::table('vocabulary')->insert(["id" => 148,"course" => 2,"kana" => "サ","kanji" => "サ", "polish" => "sa"]);
        DB::table('vocabulary')->insert(["id" => 149,"course" => 2,"kana" => "シ","kanji" => "シ", "polish" => "shi"]);
        DB::table('vocabulary')->insert(["id" => 150,"course" => 2,"kana" => "ス","kanji" => "ス", "polish" => "su"]);
        DB::table('vocabulary')->insert(["id" => 151,"course" => 2,"kana" => "セ","kanji" => "セ", "polish" => "se"]);
        DB::table('vocabulary')->insert(["id" => 152,"course" => 2,"kana" => "ソ","kanji" => "ソ", "polish" => "so"]);
        DB::table('vocabulary')->insert(["id" => 153,"course" => 2,"kana" => "タ","kanji" => "タ", "polish" => "ta"]);
        DB::table('vocabulary')->insert(["id" => 154,"course" => 2,"kana" => "チ","kanji" => "チ", "polish" => "chi"]);
        DB::table('vocabulary')->insert(["id" => 155,"course" => 2,"kana" => "ヤ","kanji" => "ヤ", "polish" => "ya"]);
        DB::table('vocabulary')->insert(["id" => 156,"course" => 2,"kana" => "ユ","kanji" => "ユ", "polish" => "yu"]);
        DB::table('vocabulary')->insert(["id" => 157,"course" => 2,"kana" => "ヨ","kanji" => "ヨ", "polish" => "yo"]);
        DB::table('vocabulary')->insert(["id" => 158,"course" => 2,"kana" => "ワ","kanji" => "ワ", "polish" => "wa"]);
        DB::table('vocabulary')->insert(["id" => 159,"course" => 2,"kana" => "ヲ","kanji" => "ヲ", "polish" => "wo"]);
        DB::table('vocabulary')->insert(["id" => 160,"course" => 2,"kana" => "ハ","kanji" => "ハ", "polish" => "ha"]);
        DB::table('vocabulary')->insert(["id" => 161,"course" => 2,"kana" => "ヒ","kanji" => "ヒ", "polish" => "hi"]);
        DB::table('vocabulary')->insert(["id" => 162,"course" => 2,"kana" => "フ","kanji" => "フ", "polish" => "fu"]);
        DB::table('vocabulary')->insert(["id" => 163,"course" => 2,"kana" => "ヘ","kanji" => "ヘ", "polish" => "he"]);
        DB::table('vocabulary')->insert(["id" => 164,"course" => 2,"kana" => "ホ","kanji" => "ホ", "polish" => "ho"]);
        DB::table('vocabulary')->insert(["id" => 165,"course" => 2,"kana" => "パ","kanji" => "パ", "polish" => "pa"]);
        DB::table('vocabulary')->insert(["id" => 166,"course" => 2,"kana" => "ピ","kanji" => "ピ", "polish" => "pi"]);
        DB::table('vocabulary')->insert(["id" => 167,"course" => 2,"kana" => "プ","kanji" => "プ", "polish" => "pu"]);
        DB::table('vocabulary')->insert(["id" => 168,"course" => 2,"kana" => "ペ","kanji" => "ペ", "polish" => "pe"]);
        DB::table('vocabulary')->insert(["id" => 169,"course" => 2,"kana" => "ポ","kanji" => "ポ", "polish" => "po"]);
        DB::table('vocabulary')->insert(["id" => 170,"course" => 2,"kana" => "ガ","kanji" => "ガ", "polish" => "ga"]);
        DB::table('vocabulary')->insert(["id" => 171,"course" => 2,"kana" => "ギ","kanji" => "ギ", "polish" => "gi"]);
        DB::table('vocabulary')->insert(["id" => 172,"course" => 2,"kana" => "グ","kanji" => "グ", "polish" => "gu"]);
        DB::table('vocabulary')->insert(["id" => 173,"course" => 2,"kana" => "ゲ","kanji" => "ゲ", "polish" => "ge"]);
        DB::table('vocabulary')->insert(["id" => 174,"course" => 2,"kana" => "ゴ","kanji" => "ゴ", "polish" => "go"]);
        DB::table('vocabulary')->insert(["id" => 175,"course" => 2,"kana" => "ダ","kanji" => "ダ", "polish" => "da"]);
        DB::table('vocabulary')->insert(["id" => 176,"course" => 2,"kana" => "ヅ","kanji" => "ヅ", "polish" => "du"]);
        DB::table('vocabulary')->insert(["id" => 177,"course" => 2,"kana" => "デ","kanji" => "デ", "polish" => "de"]);
        DB::table('vocabulary')->insert(["id" => 178,"course" => 2,"kana" => "ド","kanji" => "ド", "polish" => "do"]);
        DB::table('vocabulary')->insert(["id" => 179,"course" => 2,"kana" => "ラ","kanji" => "ラ", "polish" => "ra"]);
        DB::table('vocabulary')->insert(["id" => 180,"course" => 2,"kana" => "リ","kanji" => "リ", "polish" => "ri"]);
        DB::table('vocabulary')->insert(["id" => 181,"course" => 2,"kana" => "ル","kanji" => "ル", "polish" => "ru"]);
        DB::table('vocabulary')->insert(["id" => 182,"course" => 2,"kana" => "レ","kanji" => "レ", "polish" => "re"]);
        DB::table('vocabulary')->insert(["id" => 183,"course" => 2,"kana" => "ロ","kanji" => "ロ", "polish" => "ro"]);
        DB::table('vocabulary')->insert(["id" => 184,"course" => 2,"kana" => "ザ","kanji" => "ザ", "polish" => "za"]);
        DB::table('vocabulary')->insert(["id" => 185,"course" => 2,"kana" => "ジ","kanji" => "ジ", "polish" => "ji"]);
        DB::table('vocabulary')->insert(["id" => 186,"course" => 2,"kana" => "ズ","kanji" => "ズ", "polish" => "zu"]);
        DB::table('vocabulary')->insert(["id" => 187,"course" => 2,"kana" => "ゼ","kanji" => "ゼ", "polish" => "ze"]);
        DB::table('vocabulary')->insert(["id" => 188,"course" => 2,"kana" => "ゾ","kanji" => "ゾ", "polish" => "zo"]);
        DB::table('vocabulary')->insert(["id" => 189,"course" => 2,"kana" => "ン","kanji" => "ン", "polish" => "n"]);
        DB::table('vocabulary')->insert(["id" => 190,"course" => 2,"kana" => "ツ","kanji" => "ツ", "polish" => "tsu"]);
        DB::table('vocabulary')->insert(["id" => 191,"course" => 2,"kana" => "テ","kanji" => "テ", "polish" => "te"]);
        DB::table('vocabulary')->insert(["id" => 192,"course" => 2,"kana" => "ト","kanji" => "ト", "polish" => "to"]);
        DB::table('vocabulary')->insert(["id" => 193,"course" => 2,"kana" => "ナ","kanji" => "ナ", "polish" => "na"]);
        DB::table('vocabulary')->insert(["id" => 194,"course" => 2,"kana" => "ニ","kanji" => "ニ", "polish" => "ni"]);
        DB::table('vocabulary')->insert(["id" => 195,"course" => 2,"kana" => "ヌ","kanji" => "ヌ", "polish" => "nu"]);
        DB::table('vocabulary')->insert(["id" => 196,"course" => 2,"kana" => "ネ","kanji" => "ネ", "polish" => "ne"]);
        DB::table('vocabulary')->insert(["id" => 197,"course" => 2,"kana" => "ノ","kanji" => "ノ", "polish" => "no"]);
        DB::table('vocabulary')->insert(["id" => 198,"course" => 2,"kana" => "マ","kanji" => "マ", "polish" => "ma"]);
        DB::table('vocabulary')->insert(["id" => 199,"course" => 2,"kana" => "ミ","kanji" => "ミ", "polish" => "mi"]);
        DB::table('vocabulary')->insert(["id" => 200,"course" => 2,"kana" => "ム","kanji" => "ム", "polish" => "mu"]);
        DB::table('vocabulary')->insert(["id" => 201,"course" => 2,"kana" => "メ","kanji" => "メ", "polish" => "me"]);
        DB::table('vocabulary')->insert(["id" => 202,"course" => 2,"kana" => "モ","kanji" => "モ", "polish" => "mo"]);
        DB::table('vocabulary')->insert(["id" => 203,"course" => 6,"kana" => "あきはばら","kanji" => "秋葉原", "polish" => "Akihabara"]);
        DB::table('vocabulary')->insert(["id" => 204,"course" => 6,"kana" => "とうきょう","kanji" => "東京", "polish" => "Tokio"]);
        DB::table('vocabulary')->insert(["id" => 205,"course" => 6,"kana" => "おおさか","kanji" => "大阪", "polish" => "Osaka"]);
        DB::table('vocabulary')->insert(["id" => 206,"course" => 6,"kana" => "きょうと","kanji" => "京都", "polish" => "Kioto"]);
        DB::table('vocabulary')->insert(["id" => 207,"course" => 6,"kana" => "ひびや","kanji" => "日比谷", "polish" => "Hibiya"]);
        DB::table('vocabulary')->insert(["id" => 208,"course" => 6,"kana" => "みのわ","kanji" => "三ノ輪", "polish" => "Minowa"]);
        DB::table('vocabulary')->insert(["id" => 209,"course" => 6,"kana" => "よよぎ","kanji" => "代々木", "polish" => "Yoyogi"]);
        DB::table('vocabulary')->insert(["id" => 210,"course" => 6,"kana" => "しぶや","kanji" => "渋谷", "polish" => "Shibuya"]);
        DB::table('vocabulary')->insert(["id" => 211,"course" => 6,"kana" => "しんじゅく","kanji" => "新宿", "polish" => "Shinjuku"]);
        DB::table('vocabulary')->insert(["id" => 212,"course" => 6,"kana" => "みなみせんじゅう","kanji" => "南千住", "polish" => "Minami Senju"]);
        DB::table('vocabulary')->insert(["id" => 213,"course" => 6,"kana" => "うえの","kanji" => "上野", "polish" => "Ueno"]);
        DB::table('vocabulary')->insert(["id" => 214,"course" => 6,"kana" => "ひろしま","kanji" => "広島", "polish" => "Hiroshima"]);
        DB::table('vocabulary')->insert(["id" => 215,"course" => 6,"kana" => "いつくしま","kanji" => "厳島", "polish" => "Itsukushima"]);
        DB::table('vocabulary')->insert(["id" => 216,"course" => 6,"kana" => "おおくのしま","kanji" => "大久野島", "polish" => "Okunoshima"]);
        DB::table('vocabulary')->insert(["id" => 217,"course" => 6,"kana" => "ふくやま","kanji" => "福山", "polish" => "Fukuyama"]);
        DB::table('vocabulary')->insert(["id" => 218,"course" => 6,"kana" => "よこはま","kanji" => "横浜", "polish" => "Yokohama"]);
        DB::table('vocabulary')->insert(["id" => 219,"course" => 6,"kana" => "みしま","kanji" => "三島", "polish" => "Mishima"]);
        DB::table('vocabulary')->insert(["id" => 220,"course" => 6,"kana" => "ひめじ","kanji" => "姫路", "polish" => "Himeji"]);
        DB::table('vocabulary')->insert(["id" => 221,"course" => 6,"kana" => "こうべ","kanji" => "神戸", "polish" => "Kobe"]);
        DB::table('vocabulary')->insert(["id" => 222,"course" => 6,"kana" => "やくしま","kanji" => "屋久島", "polish" => "Yakushima"]);
        DB::table('vocabulary')->insert(["id" => 223,"course" => 8,"kana" => "ちゅうしゃ（する）","kanji" => "駐車（する）", "polish" => "parkowac"]);
        DB::table('vocabulary')->insert(["id" => 224,"course" => 8,"kana" => "まんしゃ","kanji" => "満車", "polish" => "pelny parking"]);
        DB::table('vocabulary')->insert(["id" => 225,"course" => 8,"kana" => "くうしゃ","kanji" => "空車", "polish" => "parking z wolnymi miejscami"]);
        DB::table('vocabulary')->insert(["id" => 226,"course" => 8,"kana" => "むだん（で）","kanji" => "無断（で）", "polish" => "bez pozwolenia"]);
        DB::table('vocabulary')->insert(["id" => 227,"course" => 8,"kana" => "だいきん","kanji" => "代金", "polish" => "oplata"]);
        DB::table('vocabulary')->insert(["id" => 228,"course" => 8,"kana" => "すいどう","kanji" => "水道", "polish" => "zaopatrzenie w wode"]);
        DB::table('vocabulary')->insert(["id" => 229,"course" => 8,"kana" => "ふまん（な）","kanji" => "不満（な）", "polish" => "niezadowolenie"]);
        DB::table('vocabulary')->insert(["id" => 230,"course" => 8,"kana" => "せいかく（な）","kanji" => "正確（な）", "polish" => "poprawny"]);
        DB::table('vocabulary')->insert(["id" => 231,"course" => 8,"kana" => "しんよう","kanji" => "信用", "polish" => "zaufanie"]);
        DB::table('vocabulary')->insert(["id" => 232,"course" => 8,"kana" => "ほうこう","kanji" => "方向", "polish" => "kierunek"]);
        DB::table('vocabulary')->insert(["id" => 233,"course" => 8,"kana" => "しゅっせきする","kanji" => "出席する", "polish" => "uczęszczać"]);
        DB::table('vocabulary')->insert(["id" => 234,"course" => 8,"kana" => "すうしき","kanji" => "数式", "polish" => "równanie"]);
        DB::table('vocabulary')->insert(["id" => 235,"course" => 8,"kana" => "てんじょう","kanji" => "天井", "polish" => "sufit"]);
        DB::table('vocabulary')->insert(["id" => 236,"course" => 8,"kana" => "もくじ","kanji" => "目次", "polish" => "spis treści"]);
        DB::table('vocabulary')->insert(["id" => 237,"course" => 8,"kana" => "かんしん","kanji" => "関心", "polish" => "zainteresowanie"]);
        DB::table('vocabulary')->insert(["id" => 238,"course" => 8,"kana" => "けっせき","kanji" => "欠席", "polish" => "nieobecność"]);
        DB::table('vocabulary')->insert(["id" => 239,"course" => 8,"kana" => "みらい","kanji" => "未来", "polish" => "przyszłość"]);
        DB::table('vocabulary')->insert(["id" => 240,"course" => 8,"kana" => "しま","kanji" => "島", "polish" => "wyspa"]);
        DB::table('vocabulary')->insert(["id" => 241,"course" => 8,"kana" => "わかい","kanji" => "若い", "polish" => "młody"]);
        DB::table('vocabulary')->insert(["id" => 242,"course" => 8,"kana" => "しゅっけつ","kanji" => "出血", "polish" => "krwawienie"]);
        DB::table('vocabulary')->insert(["id" => 243,"course" => 8,"kana" => "げんご","kanji" => "言語", "polish" => "język"]);
        DB::table('vocabulary')->insert(["id" => 244,"course" => 8,"kana" => "こうこく","kanji" => "広告", "polish" => "reklamy"]);
        DB::table('vocabulary')->insert(["id" => 245,"course" => 8,"kana" => "きょうつう","kanji" => "共通", "polish" => "wspólny"]);
        DB::table('vocabulary')->insert(["id" => 246,"course" => 8,"kana" => "たすける","kanji" => "助ける", "polish" => "pomagać"]);
        DB::table('vocabulary')->insert(["id" => 247,"course" => 8,"kana" => "できあがる","kanji" => "できあがる", "polish" => "być ukończonym"]);
        DB::table('vocabulary')->insert(["id" => 248,"course" => 8,"kana" => "しおからい","kanji" => "塩辛い", "polish" => "słony"]);
        DB::table('vocabulary')->insert(["id" => 249,"course" => 8,"kana" => "くわえる","kanji" => "加える", "polish" => "dodawać"]);
        DB::table('vocabulary')->insert(["id" => 250,"course" => 8,"kana" => "きざむ","kanji" => "刻む", "polish" => "siekać"]);
        DB::table('vocabulary')->insert(["id" => 251,"course" => 8,"kana" => "おゆをわかす","kanji" => "お湯を沸かす", "polish" => "zagotować wodę"]);
        DB::table('vocabulary')->insert(["id" => 252,"course" => 8,"kana" => "おゆをさます","kanji" => "お湯を冷ます", "polish" => "ostudzić wodę"]);
        DB::table('vocabulary')->insert(["id" => 253,"course" => 8,"kana" => "ごはんをたく","kanji" => "ご飯を炊く", "polish" => "ugotować ryż"]);
        DB::table('vocabulary')->insert(["id" => 254,"course" => 8,"kana" => "ゆでる","kanji" => "ゆでる", "polish" => "gotować"]);
        DB::table('vocabulary')->insert(["id" => 255,"course" => 8,"kana" => "みずをきる","kanji" => "水を切る", "polish" => "wysuszyć"]);
        DB::table('vocabulary')->insert(["id" => 256,"course" => 8,"kana" => "こしょうをふる","kanji" => "こしょうを振る", "polish" => "posypać pieprzem"]);
        DB::table('vocabulary')->insert(["id" => 257,"course" => 8,"kana" => "こさじ","kanji" => "小さじ", "polish" => "łyżeczka"]);
        DB::table('vocabulary')->insert(["id" => 258,"course" => 8,"kana" => "おおさじ","kanji" => "大さじ", "polish" => "łyżka stołowa"]);
        DB::table('vocabulary')->insert(["id" => 259,"course" => 8,"kana" => "すいはんき","kanji" => "炊飯器", "polish" => "maszyna do gotowania ryżu"]);
        DB::table('vocabulary')->insert(["id" => 260,"course" => 8,"kana" => "さます","kanji" => "覚ます", "polish" => "obudzić kogoś"]);
        DB::table('vocabulary')->insert(["id" => 261,"course" => 9,"kana" => "ていしゃ","kanji" => "停車", "polish" => "zatrzymać pojazd"]);
        DB::table('vocabulary')->insert(["id" => 262,"course" => 9,"kana" => "バスてい","kanji" => "バス停", "polish" => "przystanek autobusowy"]);
        DB::table('vocabulary')->insert(["id" => 263,"course" => 9,"kana" => "せいり","kanji" => "整理", "polish" => "porządek"]);
        DB::table('vocabulary')->insert(["id" => 264,"course" => 9,"kana" => "ちゅうしゃけん","kanji" => "駐車券", "polish" => "bilet parkingowy"]);
        DB::table('vocabulary')->insert(["id" => 265,"course" => 9,"kana" => "げんきん","kanji" => "現金", "polish" => "gotówka"]);
        DB::table('vocabulary')->insert(["id" => 266,"course" => 9,"kana" => "きがえる","kanji" => "着替える", "polish" => "przebrać się"]);
        DB::table('vocabulary')->insert(["id" => 267,"course" => 9,"kana" => "りょうがえ","kanji" => "両替", "polish" => "wymiana (np. walut)"]);
        DB::table('vocabulary')->insert(["id" => 268,"course" => 9,"kana" => "ゆうせんせき","kanji" => "優先席", "polish" => "siedzenie dla osób niepełnosprawnych"]);
        DB::table('vocabulary')->insert(["id" => 269,"course" => 9,"kana" => "じょゆう","kanji" => "女優", "polish" => "aktorka"]);
        DB::table('vocabulary')->insert(["id" => 270,"course" => 9,"kana" => "やさしい","kanji" => "優しい", "polish" => "delikatny"]);
        DB::table('vocabulary')->insert(["id" => 271,"course" => 9,"kana" => "ざせき","kanji" => "座席", "polish" => "siedzenie"]);
        DB::table('vocabulary')->insert(["id" => 272,"course" => 9,"kana" => "せいざ","kanji" => "正座", "polish" => "seiza (siedzenie w japońskim stylu)"]);
        DB::table('vocabulary')->insert(["id" => 273,"course" => 9,"kana" => "すわる","kanji" => "座る", "polish" => "siadać"]);
        DB::table('vocabulary')->insert(["id" => 274,"course" => 9,"kana" => "こうしゃぐち","kanji" => "降車口", "polish" => "wyjście (np. z autobusu)"]);
        DB::table('vocabulary')->insert(["id" => 275,"course" => 9,"kana" => "おりる","kanji" => "降りる", "polish" => "wysiadać"]);
        DB::table('vocabulary')->insert(["id" => 276,"course" => 9,"kana" => "いこう","kanji" => "以降", "polish" => "po ..."]);
        DB::table('vocabulary')->insert(["id" => 277,"course" => 9,"kana" => "していせき","kanji" => "指定席", "polish" => "zarezerwowane miejsce"]);
        DB::table('vocabulary')->insert(["id" => 278,"course" => 9,"kana" => "りょうきん","kanji" => "料金", "polish" => "opłata"]);
        DB::table('vocabulary')->insert(["id" => 279,"course" => 9,"kana" => "ちょうみりょう","kanji" => "調味料", "polish" => "przyprawy"]);
        DB::table('vocabulary')->insert(["id" => 280,"course" => 9,"kana" => "まないた","kanji" => "まな板", "polish" => "deska do krojenia"]);
        DB::table('vocabulary')->insert(["id" => 281,"course" => 9,"kana" => "す","kanji" => "酢", "polish" => "ocet"]);
        DB::table('vocabulary')->insert(["id" => 282,"course" => 9,"kana" => "はかり","kanji" => "はかり", "polish" => "waga"]);
        DB::table('vocabulary')->insert(["id" => 283,"course" => 9,"kana" => "えいよう","kanji" => "栄養", "polish" => "składniki odżywcze"]);
        DB::table('vocabulary')->insert(["id" => 284,"course" => 9,"kana" => "じゅうたん","kanji" => "じゅうたん", "polish" => "dywan"]);
        DB::table('vocabulary')->insert(["id" => 285,"course" => 10,"kana" => "りそう","kanji" => "理想", "polish" => "ideał"]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('vocabulary');
    }
}
